nginx-ingress:
  controller:
    hostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet
    extraArgs: {
      default-ssl-certificate: "default/paul-steele.com"
    }
    service:
      loadBalancerIP: "192.168.0.200"
