apiVersion: v1
kind: PersistentVolume
metadata:
  name: docker-registry
  labels:
    type: local
spec:
  storageClassName: docker-registry
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/paul/docker-registry"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-registry
spec: 
  storageClassName: docker-registry
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
