apiVersion: v1
kind: Service
metadata:
  name: duplicati
spec:
  type: NodePort
  selector:
    app: duplicati
  ports:
    - protocol: TCP
      port: 8200
      nodePort: 30000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: duplicati
  labels:
    app: duplicati
spec:
  replicas: 1
  selector:
    matchLabels:
      app: duplicati
  template:
    metadata:
      labels:
        app: duplicati
    spec:
      containers:
        - name: reader
          image: linuxserver/duplicati
          ports:
            - containerPort: 8200
          volumeMounts:
            - name: config
              mountPath: "/config"
            - name: source
              mountPath: "/source"
      volumes:
        - name: config
          hostPath:
            type: Directory
            path: /home/paul/duplicati/config
        - name: source
          hostPath:
            type: Directory
            path: /home/paul
