apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: firefly
spec:
  rules:
    - host: finance.paul-steele.com
      http:
        paths:
          - backend:
              serviceName: firefly
              servicePort: 80
            path: /
  tls:
    - hosts:
        - finance.paul-steele.com
---
apiVersion: v1
kind: Service
metadata:
  name: firefly
spec:
  selector:
    app: firefly
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: firefly
  labels:
    app: firefly
spec:
  replicas: 1
  selector:
    matchLabels:
      app: firefly
  template: 
    metadata:
      labels:
        app: firefly
    spec:
      containers:
        - name: firefly
          image: jc5x/firefly-iii:latest
          ports: 
            - containerPort: 80
          env:
            - name: FF_DB_HOST
              value: database-mysql:3306
            - name: FF_DB_USER
              value: eos
            - name: FF_DB_NAME
              value: firefly_db
            - name: FF_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-mysql
                  key: mysql-password
            - name: FF_APP_KEY
              valueFrom:
                secretKeyRef:
                  name: firefly-token
                  key: FF_APP_KEY
            - name: FF_APP_ENV
              value: local
            - name: APP_URL
              value: https://finance.paul-steele.com
            - name: TRUSTED_PROXIES
              value: "**"
          volumeMounts:
            - name: storage
              mountPath: "/var/www/firefly-iii/storage"
      volumes:
        - name: storage
          hostPath:
            type: Directory
            path: /home/paul/firefly/volumes/app
