apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: reader
spec:
  rules:
    - host: reader.paul-steele.com
      http:
        paths:
          - backend:
              serviceName: reader
              servicePort: 80
            path: /
  tls:
    - secretName: paul-steele.com
      hosts:
        - reader.paul-steele.com
---
apiVersion: v1
kind: Service
metadata:
  name: reader
spec:
  selector:
    app: reader
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reader
  labels:
    app: reader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reader
  template:
    metadata:
      labels:
        app: reader
    spec:
      containers:
        - name: reader
          image: linuxserver/freshrss
          ports:
            - containerPort: 80
          env:
            - name: CRON_MIN
              value: '5,35'
          volumeMounts:
            - name: data
              mountPath: "/var/www/FreshRSS/data"
      volumes:
        - name: data
          hostPath:
            type: Directory
            path: /home/paul/freshrss/data
