apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: homeassistant
spec:
  rules:
    - host: home.paul-steele.com
      http:
        paths:
          - backend:
              serviceName: homeassistant
              servicePort: 80
            path: /
  tls:
    - secretName: paul-steele.com
      hosts:
        - home.paul-steele.com
---
apiVersion: v1
kind: Service
metadata:
  name: homeassistant
spec:
  selector:
    app: homeassistant
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8123
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homeassistant-systemd-services
data:
  zwave: |
    #!/bin/bash
    case "$1" in 
        start)
          socat pty,link=/dev/ttyUSB0,raw,user=0,group=0,mode=777 tcp:192.168.0.110:3333 &
          ;;
        stop)
          stop
          ;;
        restart)
          stop
          start
          ;;
        status)
          # code to check status of app comes here 
          # example: status program_name
          ;;
        *)
          echo "Usage: $0 {start|stop|status|restart}"
    esac

    exit 0 
  zha: |
    #!/bin/bash
    case "$1" in 
        start)
          socat pty,link=/dev/ttyUSB1,raw,user=0,group=0,mode=777 tcp:192.168.0.110:3334 &
          ;;
        stop)
          stop
          ;;
        restart)
          stop
          start
          ;;
        status)
          # code to check status of app comes here 
          # example: status program_name
          ;;
        *)
          echo "Usage: $0 {start|stop|status|restart}"
    esac

    exit 0 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeassistant
  labels:
    app: homeassistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homeassistant
  template: 
    metadata:
      labels:
        app: homeassistant
    spec:
      containers:
        - name: homeassistant
          image: homeassistant/home-assistant
          ports: 
            - containerPort: 8123
            - containerPort: 8300
          command: ["sh"]
          args: ["-c", "apt-get update && apt-get install socat && service zwave start && python -m homeassistant --config /config"]
          volumeMounts:
            - name: config
              mountPath: "/config"
            - name: zwave-config
              mountPath: /etc/init.d/zwave
              subPath: zwave
            - name: zha-config
              mountPath: /etc/init.d/zha
              subPath: zha
        - name: zrc-90-listener
          image: registry.paul-steele.com/zrc-90:latest
          env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: homeassistant
                  key: APP_KEY
            - name: API_URI
              value: http://localhost:8123/api/events/custom_scene
            - name: MASTER_NODE
              value: Node009
          volumeMounts:
            - name: config
              mountPath: "/home/hass/hass"
      imagePullSecrets:
        - name: registry.paul-steele.com
      volumes:
        - name: config
          hostPath:
            type: Directory
            path: /home/paul/homeassistant/volumes/homeassistant
        - name: zwave-config
          configMap:
            name: homeassistant-systemd-services
            defaultMode: 0755
            items: 
              - key: zwave
                path: zwave
        - name: zha-config
          configMap:
            defaultMode: 0755
            name: homeassistant-systemd-services
            items: 
              - key: zha
                path: zha