kind: ServiceAccount
apiVersion: v1
metadata:
  name: deployments
  namespace: default
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: ci-jenkins
  namespace: default
automountServiceAccountToken: false
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: deployments
rules:
  - apiGroups: ["apps", "extensions", ""]
    resources: ["pods", "services", "deployments", "ingresses", "configmaps"]
    verbs: ["*"]
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ci-jenkins
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: deployments
  namespace: deployments
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: deployments
subjects:
  - kind: ServiceAccount
    name: deployments
    namespace: default
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: ci-jenkins
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ci-jenkins
subjects:
  - kind: ServiceAccount
    name: ci-jenkins
    namespace: default
