apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: mirror
spec:
  rules:
    - host: mirror.paul-steele.com
      http:
        paths:
          - backend:
              serviceName: mirror
              servicePort: 80
            path: /
  tls:
    - hosts:
        - mirror.paul-steele.com
---
apiVersion: v1
kind: Service
metadata:
  name: mirror
spec:
  selector:
    app: mirror
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mirror
  labels:
    app: mirror
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mirror
  template:
    metadata:
      labels:
        app: mirror
    spec:
      containers:
        - name: mirror
          image: bastilimbach/docker-magicmirror
          ports:
            - containerPort: 8080
          env:
          volumeMounts:
            - name: config
              mountPath: "/opt/magic_mirror/config"
      volumes:
        - name: config
          configMap:
            name: mirror