apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: mysqldump
spec:
  schedule: "0 1 * * 4"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: mysqldump 
              image: camil/mysqldump
              env:
                - name: ALL_DATABASES
                  value: "true"
                - name: DB_HOST
                  value: database-mysql
                - name: DB_USER
                  value: eos
                - name: DB_PASS
                  valueFrom:
                    secretKeyRef:
                      name: database-mysql
                      key: mysql-password
              command: ["/bin/bash"]
              args: ["-c", "chmod +x dump.sh && ./dump.sh"]
              volumeMounts:
                - mountPath: /mysqldump
                  name: mysqldump
          volumes:
            - name: mysqldump
              hostPath:
                type: Directory
                path: /home/paul/database-backup/mysql
          restartPolicy: Never
