apiVersion: v1
kind: PersistentVolume
metadata:
  name: alertmanager
  namespace: prometheus
  labels:
    type: local
spec:
  storageClassName: alertmanager
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/paul/prometheus/alertmanager"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alertmanager
  namespace: prometheus
spec: 
  storageClassName: alertmanager
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus
  namespace: prometheus
  labels:
    type: local
spec:
  storageClassName: prometheus
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/paul/prometheus/prometheus"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus
  namespace: prometheus
spec: 
  storageClassName: prometheus
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
