apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: subsonic
spec:
  rules:
    - host: media.paul-steele.com
      http:
        paths:
          - backend:
              serviceName: subsonic
              servicePort: 8080
            path: /
  tls:
    - hosts:
        - media.paul-steele.com
---
apiVersion: v1
kind: Service
metadata:
  name: subsonic
spec:
  selector:
    app: subsonic
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: subsonic
  labels:
    app: subsonic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subsonic
  template:
    metadata:
      labels:
        app: subsonic
    spec:
      containers:
        - name: subsonic
          image: mbirth/subsonic
          ports:
            - containerPort: 8080
          env:
            - name: TZ
              value: America/Indiana/Indianapolis
          volumeMounts:
            - name: config
              mountPath: "/subsonic"
            - name: music
              mountPath: "/music"
            - name: data
              mountPath: "/data"
      volumes:
        - name: config
          hostPath:
            type: DirectoryOrCreate
            path: /home/paul/subsonic/config
        - name: data
          hostPath:
            type: DirectoryOrCreate
            path: /home/paul/subsonic/data
        - name: music
          hostPath:
            type: Directory
            path: /home/paul/plex/volumes/media/music/Music
