apiVersion: v2
name: tekton
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: 1.15.0
dependencies:
- name: base
  version: 0.1.0
  repository: file://../base
- name: dashboard
  version: 0.6.4
  repository: https://eddycharly.github.io/tekton-helm
- name: pipelines
  version: 0.12.0
  repository: https://eddycharly.github.io/tekton-helm
- name: triggers
  version: 0.4.0
  repository: https://eddycharly.github.io/tekton-helm
