apiVersion: v2
name: tekton
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: 1.15.0
dependencies:
- name: base
  version: 0.1.0
  repository: file://../base
- name: dashboard
  version: 0.6.1
  repository: git+https://github.com/tektoncd/experimental.git@helm/dashboard?ref=aa3d3db13e0ac9d1c3a8a3524a82a95be2761b7d&sparse=0
- name: pipeline
  version: 0.11.3
  repository: git+https://github.com/tektoncd/experimental.git@helm/pipeline?ref=aa3d3db13e0ac9d1c3a8a3524a82a95be2761b7d&sparse=0
- name: triggers
  version: 0.4.0
  repository: git+https://github.com/tektoncd/experimental.git@helm/triggers?ref=aa3d3db13e0ac9d1c3a8a3524a82a95be2761b7d&sparse=0
