baseResources:
  clusterTasks:
  - name: container-build
    params:
    - name: git_url
      type: string
    - name: repo_name
      type: string
    - name: sha
      type: string
    - name: docker_registry
      type: string
    steps:
    - name: clone
      image: alpine/git
      command:
      - git
      args:
      - clone
      - "$(params.git_url)"
    - name: build
      registryAccess: true
      image: gcr.io/kaniko-project/executor
      args:
      - "--dockerfile=/workspace/project/$(params.repo_name)/Dockerfile"
      - "--context=dir:///workspace/project/$(params.repo_name)"
      - "--destination=registry.paul-steele.com/$(params.docker_registry):$(params.sha)"
    - name: prepare-manifest
      image: loicmahieu/alpine-envsubst
      env:
      - name: BUILD_TAG
        value: "$(params.sha)"
      command:
      - sh
      args:
      - "-c"
      - "envsubst < /workspace/project/$(params.repo_name)/k8s.template.yaml > /workspace/project/$(params.repo_name)/k8s.yaml"
    - name: deploy
      image: lachlanevenson/k8s-kubectl:v1.15.0
      command:
      - kubectl
      args:
      - "apply"
      - "-f"
      - "/workspace/project/$(params.repo_name)/k8s.yaml"
  clusterTriggerBindings:
  - name: github
    params:
    - name: git_url
      value: $(body.repository.clone_url)
    - name: repo_name
      value: $(body.repository.name)
    - name: sha
      value: $(body.head_commit.id)
