baseResources:
  ingress:
    host: ci.paul-steele.com
    serviceName: ci-dashboard
    port: 9097
dashboard:
  dashboard:
    readOnly: true
  customResourceDefinitions:
    create: false
pipeline:
  customResourceDefinitions:
    create: false
triggers:
  customResourceDefinitions:
    create: true
