baseResources:
  ingresses:
  - name: tekton-ci
    host: ci.paul-steele.com
    serviceName: ci-dashboard
    port: 9097
    auth: true
  - name: tekton-triggers
    host: triggers.paul-steele.com
    serviceName: el-ci-listener
    port: 8080
  serviceAccounts:
  - name: triggers
  clusterRoles:
  - name: triggers
    rules:
    - apiGroups:
      - triggers.tekton.dev
      resources:
      - eventlisteners
      - triggerbindings
      - clustertriggerbindings
      - triggertemplates
      verbs:
      - get
    - apiGroups:
      - tekton.dev
      resources:
      - pipelineruns
      - pipelineresources
      verbs:
      - create
    - apiGroups:
      - '""'
      resources:
      - configmaps
      - secrets
      verbs:
      - get
      - list
      - watch
  clusterRoleBindings:
  - name: triggers
    serviceAccountName: triggers
    serviceAccountNamespace: default
    clusterRoleName: triggers
  clusterTasks:
  - name: checkout
    params:
    - name: git_url
      type: string
    steps:
    - name: clone
      image: alpine/git
      command:
      - git
      args:
      - clone
      - "$(params.url)"
  clusterTriggerBindings:
  - name: github
    params:
    - name: git_url
      value: $(body.repository.clone_url)
  pipelines:
  - name: blog
    tasks:
    - name: checkout1
      taskRef: checkout
    - name: checkout2
      taskRef: checkout
  triggerTemplates:
  - name: blog
    pipeline: blog
  eventListeners:
  - name: ci-listener
    serviceAccountName: triggers
    triggers:
    - name: blog
      template: blog
      url: 'https://github.com/paulsteele/blog'
