baseResources:
  ingress:
    host: ci.paul-steele.com
    serviceName: ci-dashboard
    port: 9097
    auth: true
  clusterTasks:
  - name: checkout
    params:
    - name: git_url
      type: string
    steps:
    - name: clone
      image: alpine/git
      command:
      - git
      args:
      - clone
      - "$(params.url)"
  clusterTriggerBindings:
  - name: github
    params:
    - name: git_url
      value: $(body.repository.clone_url)
