baseResources:
  ingresses:
  - name: tekton-ci
    host: ci.paul-steele.com
    serviceName: ci-dashboard
    port: 9097
    auth: true
  - name: tekton-triggers
    host: triggers.paul-steele.com
    serviceName: el-ci-listener
    port: 8080
  serviceAccounts:
  - name: triggers
  - name: ci-builder
  clusterRoles:
  - name: triggers
    rules:
    - apiGroups:
      - triggers.tekton.dev
      resources:
      - eventlisteners
      - triggerbindings
      - clustertriggerbindings
      - triggertemplates
      verbs:
      - get
    - apiGroups:
      - tekton.dev
      resources:
      - pipelineruns
      - pipelineresources
      verbs:
      - create
    - apiGroups:
      - '""'
      resources:
      - configmaps
      - secrets
      verbs:
      - get
      - list
      - watch
  clusterRoleBindings:
  - name: triggers
    serviceAccountName: triggers
    serviceAccountNamespace: default
    clusterRoleName: triggers
  clusterTasks:
  - name: container-build
    params:
    - name: git_url
      type: string
    - name: repo_name
      type: string
    - name: sha
      type: string
    - name: docker_registry
      type: string
    steps:
    - name: clone
      image: alpine/git
      command:
      - git
      args:
      - clone
      - "$(params.git_url)"
    - name: build
      registryAccess: true
      image: gcr.io/kaniko-project/executor
      args:
      - "--dockerfile=/workspace/project/$(params.repo_name)/Dockerfile"
      - "--context=dir:///workspace/project/$(params.repo_name)"
      - "--destination=registry.paul-steele.com/$(params.docker_registry):$(params.sha)"
    - name: prepare-manifest
      image: loicmahieu/alpine-envsubst
      env:
      - name: BUILD_TAG
        value: "$(params.sha)"
      command:
      - sh
      args:
      - "-c"
      - "envsubst < /workspace/project/$(params.repo_name)/k8s.template.yaml > /workspace/project/$(params.repo_name)/k8s.yaml"
    - name: deploy
      image: lachlanevenson/k8s-kubectl:v1.15.0
      command:
      - kubectl
      args:
      - "apply"
      - "-f"
      - "/workspace/project/$(params.repo_name)/k8s.yaml"
  clusterTriggerBindings:
  - name: github
    params:
    - name: git_url
      value: $(body.repository.clone_url)
    - name: repo_name
      value: $(body.repository.name)
    - name: sha
      value: $(body.head_commit.id)
  pipelines:
  - name: blog
    tasks:
    - name: build
      taskRef: container-build
      params:
      - name: docker_registry
        value: blog
  triggerTemplates:
  - name: blog
    pipeline: blog
  eventListeners:
  - name: ci-listener
    serviceAccountName: triggers
    triggers:
    - name: blog
      template: blog
      url: 'https://github.com/paulsteele/blog'
