baseResources:
  ingress:
    host: ci.paul-steele.com
    serviceName: ci-dashboard
    port: 9097
    auth: true
  clusterTasks:
  - name: checkout
    params:
    - name: git_url
      type: string
    steps:
    - name: clone
      image: alpine/git
      command:
      - git
      args:
      - clone
      - "$(params.url)"
  clusterTriggerBindings:
  - name: github
    params:
    - name: git_url
      value: $(body.repository.clone_url)
  pipelines:
  - name: blog
    tasks:
    - name: checkout1
      taskRef: checkout
    - name: checkout2
      taskRef: checkout
  triggerTemplates:
  - name: blog
    pipeline: blog
  eventListeners:
  - name: ci-listener
    triggers:
    - name: blog
      template: blog
      url: 'https://github.com/paulsteele/blog'
