baseResources:
  ingresses:
  - name: tekton-ci
    host: ci.paul-steele.com
    serviceName: ci-dashboard
    port: 9097
    auth: true
  - name: tekton-triggers
    host: triggers.paul-steele.com
    serviceName: el-ci-listener
    port: 8080
  pipelines:
  - name: blog
    tasks:
    - name: build
      taskRef: container-build
      params:
      - name: docker_registry
        value: blog
  triggerTemplates:
  - name: blog
    pipeline: blog
  eventListeners:
  - name: ci-listener
    serviceAccountName: triggers
    triggers:
    - name: blog
      template: blog
      url: 'https://github.com/paulsteele/blog'
