###############################################################
#                   Authelia configuration                    #
###############################################################

host: 0.0.0.0
port: 8080
log_level: debug
default_redirection_url: https://sso.paul-steele.com

authentication_backend:
  file:
    path: /etc/authelia/users.yml

storage:
  local:
    path: /var/lib/authelia/db.sqlite3

access_control:
  default_policy: deny
  rules:
    # Rules applied to everyone
    - domain: "*.paul-steele.com"
      policy: one_factor
session:
  name: authelia_session
  expiration: 3600 # 1 hour
  inactivity: 300 # 5 minutes
  domain: paul-steele.com # Should match whatever your root protected domain is

notifier:
  filesystem:
    filename: /tmp/authelia/notification.txt

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300
