{{- define "base.clusterTriggerBindings" -}}
{{- range $index, $clusterTriggerBinding:= .Values.baseResources.clusterTriggerBindings }}
apiVersion: triggers.tekton.dev/v1alpha1
kind: ClusterTriggerBinding
metadata:
  name: {{ $clusterTriggerBinding.name }}
  {{- if $clusterTriggerBinding.params }}
spec:
  params:
  {{- range $index, $param:= $clusterTriggerBinding.params }}
  - name: {{ $param.name }}
    value: '{{ $param.value }}'
  {{- end }}
  {{- end }}
---
{{- end }}
{{- end -}}
