{{- define "base.clusterIssuer" -}}
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: {{ include "base.name" . }}
spec:
  acme:
    dns01:
      providers:
      - name: route53
        route53:
          accessKeyID: {{ .Values.baseResources.clusterIssuer.accessKeyID }}
          region: us-east-1
          secretAccessKeySecretRef:
            key: key
            name: {{ .Values.baseResources.clusterIssuer.secretName }}
    email: paul-steele@live.com
    privateKeySecretRef:
      name: letsencrypt-cert-manager
    server: https://acme-v02.api.letsencrypt.org/directory
{{- end -}}
