{{- define "base.clusterTasks" -}}
{{- range $index, $task:= .Values.baseResources.clusterTasks }}
apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: {{ $task.name }}
spec:
  {{- if $task.params }}
  params:
  {{- range $index, $param:= $task.params }}
  - name: {{ $param.name }}
    type: {{ $param.type }}
  {{- end }}
  {{- end -}}
  {{- if $task.steps }}
  steps:
  {{- range $index, $step:= $task.steps }}
  - name: {{ $step.name }}
    image: {{ $step.image }}
    workingDir: /workspace/project
    command:
    {{- range $index, $command:= $step.command }}
    - {{ $command }}
    {{- end }}
    args:
    {{- range $index, $arg:= $step.args }}
    - {{ $arg }}
    {{- end }}
    {{- if $step.env }}
    env:
    {{- range $index, $env:= $step.env }}
    - name: {{ $env.name }}
      value: {{ $env.value }}
    {{- end }}
    {{- end }}
    {{- if $step.registryAccess }}
    volumeMounts:
    - name: docker-registry
      mountPath: /kaniko/.docker/config.json
      subPath: config.json
    {{- end }}
  {{- end }}
  {{- end }}
  volumes:
  - name: docker-registry
    secret:
      secretName: registry.paul-steele.com
      items:
      - key: .dockerconfigjson
        path: config.json
  workspaces:
  - name: project
    description: The folder that contains project files
    mountPath: /workspace/project
---
{{- end }}
{{- end -}}
