{{- define "base.ingress" -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: '0'
    {{- if .Values.baseResources.ingress.auth }}
    nginx.ingress.kubernetes.io/auth-url: "https://sso.paul-steele.com/api/verify"
    nginx.ingress.kubernetes.io/auth-signin: "https://sso.paul-steele.com/"
    {{- end }}
  name: {{ include "base.name" . }}
spec:
  rules:
  - host: {{ .Values.baseResources.ingress.host }}
    http:
      paths:
      - backend:
          serviceName: {{ default ( include "base.name" . ) .Values.baseResources.ingress.serviceName }}
          servicePort: {{ .Values.baseResources.ingress.port }}
        path: /
  tls:
  - hosts:
    - {{ .Values.baseResources.ingress.host }}
{{- end -}}
