{{- define "base.ingress" -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: '0'
  name: {{ include "base.name" . }}
spec:
  rules:
  - host: {{ .Values.baseResources.ingress.host }}
    http:
      paths:
      - backend:
          serviceName: {{ include "base.name" . }}
          servicePort: {{ .Values.baseResources.ingress.port }}
        path: /
  tls:
  - hosts:
    - {{ .Values.baseResources.ingress.host }}
{{- end -}}
