{{- define "base.pipelines" -}}
{{- range $index, $pipeline:= .Values.baseResources.pipelines }}
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: {{ $pipeline.name }}
spec:
  params:
  - name: git_url
    type: string
  - name: repo_name
    type: string
  - name: sha
    type: string
  {{- range $index, $param:= $pipeline.params}}
  - name: {{ $param }}
    type: string
  {{- end }}
  tasks:
  {{- range $index, $task:= $pipeline.tasks }}
  - name: {{ $task.name }}
    taskRef:
      name: {{ $task.taskRef }}
      kind: ClusterTask
    params:
    - name: git_url
      value: "$(params.git_url)"
    - name: repo_name
      value: "$(params.repo_name)"
    - name: sha
      value: "$(params.sha)"
    {{- range $index, $param:= $pipeline.params}}
    - name: {{ $param.name }}
      value: "$(params.{{ $param.name}})"
    {{- end }}
    {{- range $index, $param:= $task.params }}
    - name: {{ $param.name }}
      value: '{{ $param.value }}'
    {{- end }}
    {{- if gt $index 0 }}
    runAfter:
      - {{ (index $pipeline.tasks (sub $index 1)).name }}
    {{- end }}
    workspaces:
    - name: project
      workspace: project
  {{- end }}
  workspaces:
  - name: project
---
{{- end }}
{{- end -}}
