{{- define "base.roleBindings" -}}
{{- range $index, $roleBinding:= .Values.baseResources.roleBindings }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $roleBinding.name }}
  namespace: {{ $roleBinding.namespace }}
subjects:
- kind: ServiceAccount
  name: {{ $roleBinding.serviceAccountName }}
  namespace: {{ $roleBinding.serviceAccountNamespace }}
roleRef:
  kind: ClusterRole
  name: {{ $roleBinding.clusterRoleName }}
  apiGroup: rbac.authorization.k8s.io

---
{{- end }}
{{- end -}}
