{{- define "base.secrets" -}}
{{- range $index, $secret := .Values.baseResources.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secret.name }}
stringData:
  {{- range $key, $val := $secret.fields }}
  {{ $key }}: "{{ $val }}"
  {{- end }}
---
{{- end }}
{{- end -}}
