{{- define "base.serviceAccounts" -}}
{{- range $index, $serviceAccount:= .Values.baseResources.serviceAccounts }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $serviceAccount.name }}
---
{{- end }}
{{- end -}}
