{{- define "base.service" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "base.name" . }}
spec:
  ports:
  - port: {{ .Values.baseResources.service.port }}
    protocol: TCP
    targetPort: {{ .Values.baseResources.service.port }}
  selector:
    app: {{ include "base.name" . }}
{{- end -}}
