{{- define "base.triggerTemplates" -}}
{{- range $index, $triggerTemplate:= .Values.baseResources.triggerTemplates }}
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: {{ $triggerTemplate.name }}
spec:
  params:
  - name: git_url
  - name: repo_name
  - name: sha
  {{- range $index, $param:= $triggerTemplate.params}}
  - name: {{ $param }}
  {{- end }}
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: {{ $triggerTemplate.pipeline }}-run-
    spec:
      serviceAccountName: ci-builder
      pipelineRef:
        name: {{ $triggerTemplate.pipeline }}
      params:
      - name: git_url
        value: "$(params.git_url)"
      - name: repo_name
        value: "$(params.repo_name)"
      - name: sha
        value: "$(params.sha)"
      {{- range $index, $param:= $triggerTemplate.params}}
      - name: {{ $param }}
        value: "$(params.{{ $param.name}})"
      {{- end }}
      workspaces:
      - name: project
        volumeClaimTemplate:
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
---
{{- end }}
{{- end -}}
