baseResources:
    secrets:
    -   name: ENC[AES256_GCM,data:0Ymwkn2i+pB0Zirv2XNM9pApxJg=,iv:odKFw55EI4jfTv6qAiXcPPvKDKVxkJNfv7cDsErdle0=,tag:X49Z63HNga3Md0EUmKDBXg==,type:str]
        fields:
            NEXTCLOUD_ADMIN_PASS: ENC[AES256_GCM,data:FAPbubyhVKuHwZkhuXsyWpEVBFvy76h55oZY0z2h3ptdU2cQ,iv:V1WAbr19frA4aFH1xUNPwmwlwzjXD1cCZV7X/seSZd4=,tag:1eaxPxFVThWYHWlBO7PEOg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2020-04-24T01:27:09Z'
    mac: ENC[AES256_GCM,data:hkuGxg5fHgfBapiIUbqy94lW+HF3YVfJwNiKFPbiq0C0dvrJTM+IMZ4ismJwXXW2doJtvx/CtRehkrlQHdrUoD6Uav35uYJZLxtUczsk2bCdy2VhiC23SHhQGG6cp8gjcqWoj44efMgDUU6eErR+4zmFENO8siHbRbhkfvfWbLM=,iv:WyVQ9EYqQ6S7vXU70NHR4ABaFcSsxcVM+ONuWFqDoac=,tag:o/ABxbPcBOE12uEHRBYhDA==,type:str]
    pgp:
    -   created_at: '2020-04-24T01:27:08Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA1Biv9gnCd8SAQf/bL30t2RGfSBYRzT/jjOMZyyt69bktyfIcnERoxeISnvj
            dN0pWd9wGP3XmL2CQENYFX4aGd0qYGzVqY4vhtR8hv5UsOW8ugB9jqlC0wZbpL7V
            CZ2M02quyEw+rcROR0DAyc0R9sxRj1ToFQOdKYRx2EOfB7I2b+Qfvw3r17rawTjA
            mJjdObTjjm9a4ZMn2CUNvLa+ss7dSbN7xIPjERLgKNDwtcRbLTd1ZGi2tGu9MpbH
            z4DKJxIeOxVOJuzlZFwd3dRg9eZB4bhTF7dlMJCih9Ddt9w7QYa2nR33+nyPgahZ
            0RfbNIKv272Sh1vbGSpkwJzFvQbroWamdni2zYLEqNJeAV/mkPSGuBacrgRDIr3l
            9usiKXoazUk10ml6p0/OwdM2hzAwDQZb9YVi/id9pTfQM13TbbKvEevkO6Y+CCz3
            iDrHEcQh8p85pjZcj11UMyrx4RyUwTD+dgAbh9/Vvw==
            =ulz8
            -----END PGP MESSAGE-----
        fp: 02B688797D1B649A6FB352756E8AC191164F2E1D
    unencrypted_suffix: _unencrypted
    version: 3.5.0
